export const proposalsArray = [
  {
    id: 1,
    username: "John Doe",
    userImage: "https://placehold.co/64x64",
    status: "In Progress",
    statusColor: "bg-blue-200 text-blue-800",
    submittedOn: "04/04/24 5:32:11 AM",
    expiresOn: "04/04/24 5:32:11 AM",
    votesRequired: 15,
    comments: 5,
    shares: 7,
    voters: 3,
    description: [
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna.",
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim",
    ],
    timeLeft: "6d 8h 35m 12s left",
  },
  {
    id: 2,
    username: "Jane Smith",
    userImage: "https://placehold.co/64x64",
    status: "Completed",
    statusColor: "bg-green-200 text-green-800",
    submittedOn: "04/04/24 6:45:22 AM",
    expiresOn: "04/04/24 6:45:22 AM",
    votesRequired: 20,
    comments: 8,
    shares: 10,
    voters: 5,
    description: [
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna.",
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim",
    ],
    timeLeft: "1d 4h 22m 18s left",
  },
  {
    id: 2,
    username: "Jane Smith",
    userImage: "https://placehold.co/64x64",
    status: "Completed",
    statusColor: "bg-green-200 text-green-800",
    submittedOn: "04/04/24 6:45:22 AM",
    expiresOn: "04/04/24 6:45:22 AM",
    votesRequired: 20,
    comments: 8,
    shares: 10,
    voters: 5,
    description: [
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna.",
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim",
    ],
    timeLeft: "1d 4h 22m 18s left",
  },
  {
    id: 2,
    username: "Jane Smith",
    userImage: "https://placehold.co/64x64",
    status: "Completed",
    statusColor: "bg-green-200 text-green-800",
    submittedOn: "04/04/24 6:45:22 AM",
    expiresOn: "04/04/24 6:45:22 AM",
    votesRequired: 20,
    comments: 8,
    shares: 10,
    voters: 5,
    description: [
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna.",
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim",
    ],
    timeLeft: "1d 4h 22m 18s left",
  },
  {
    id: 2,
    username: "Jane Smith",
    userImage: "https://placehold.co/64x64",
    status: "Completed",
    statusColor: "bg-green-200 text-green-800",
    submittedOn: "04/04/24 6:45:22 AM",
    expiresOn: "04/04/24 6:45:22 AM",
    votesRequired: 20,
    comments: 8,
    shares: 10,
    voters: 5,
    description: [
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna.",
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim",
    ],
    timeLeft: "1d 4h 22m 18s left",
  },
  {
    id: 2,
    username: "Jane Smith",
    userImage: "https://placehold.co/64x64",
    status: "Completed",
    statusColor: "bg-green-200 text-green-800",
    submittedOn: "04/04/24 6:45:22 AM",
    expiresOn: "04/04/24 6:45:22 AM",
    votesRequired: 20,
    comments: 8,
    shares: 10,
    voters: 5,
    description: [
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna.",
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim",
    ],
    timeLeft: "1d 4h 22m 18s left",
  },
];
